
package core;

/**
 * All error codes that the server can output are stored here.
 * @author max
 */
public enum ErrorCodes
{
    EVERYTHING_IS_FINE,
    ACCOUNT_DOSENT_EXIST,
    LOGIN_FAILED,
    LOGOUT_FAILED,
    AUTHORIZATION_FAILED,
    SENDING_CLIENT_DATA_FAILED,
    DATABASE_ERROR,
    ADD_COMMENT_FAILED,
    ADD_EVENT_FAILED,
    DELETE_COMMENT_FAILED,
    DELETE_EVENT_FAILED,
    GET_ALL_COMMENTS_FAILED,
    GET_ALL_EVENTS_FAILED,
    GET_CURRENT_EVENTS_FAILED,
    GET_EVENT_FAILED,
    GET_EVENT_COMMENTS_FAILED,
    GET_RESOLVED_EVENTS_FAILED,
    UPDATE_COMMENT_FAILED,
    UPDATE_EVENT_FAILED,
    SET_EVENT_RESOLVED_FAILED,
    SET_EVENT_UNRESOLVED_FAILED,
    NO_EVENTS_FOUND,
    NO_COMMENTS_FOUND,
}
